server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/firecode7/cloud2020.git  #GitHub上仓库的名字
          search-paths:
            - cloud2020/config/ #搜索目录
      label: master #读取分支
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

