server:
  port: 80


eureka:
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  hystrix:
    enabled: true


#设置Feign客户端的超时时间（OpenFeign默认支持Ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络连接状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#设置hystrix超时时长
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

